on:
  schedule:
    # Run at every 11th minute of the hour, 11 can be any value.
    - cron:  '11 * * * *'
  workflow_dispatch:
  push:


jobs:
  check-quality:
    runs-on: ubuntu-latest
    name: Datadog Static Analyzer
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check code meets quality standards
        id: datadog-static-analysis
        uses: DataDog/datadog-static-analyzer-github-action@v1
        with:
          dd_app_key: ${{ secrets.DD_APP_KEY_DEMO_ORG }}
          dd_api_key: ${{ secrets.DD_API_KEY_DEMO_ORG }}
          dd_service: "ci-visibility-code-analysis-synthetics-ci-data-source"
          dd_env: "github"
          dd_site: "datadoghq.com"
